volumes:
  wordpress:
      driver: local
      driver_opts:
        o: bind
        type: none
        device: /Users/aweizman/Desktop/inception/wordpress
  mariadb:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/aweizman/Desktop/inception/mariadb

networks:
  inception:
    name: inception

services:
  nginx:
    build: requirements/nginx/
    networks:
      - inception
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    container_name: nginx
    ports:
      - "443:443"
    env_file: requirements/.env
    restart: on-failure
  wordpress:
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    build: requirements/wordpress/
    container_name: wp-php
    env_file:
      - requirements/.env
    restart: on-failure
    networks:
      - inception
    expose:
      - "9000"
  mariadb:
    networks:
      - inception
    build: requirements/mariadb/
    container_name: mariadb
    env_file: requirements/.env
    volumes:
      - mariadb:/var/lib/mysql
    restart: on-failure
    expose:
      - "3306"
